services:
  # ============================================================
  # container_postgres_16
  # ============================================================
  container_postgres_16:
    image: postgres:16
    container_name: container_postgres_16
    restart: unless-stopped

    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres

    networks:
      - postgres_16_network

    volumes:
      - volumes_postgres_16:/var/lib/postgresql/data

    ports:
      - "5632:5432"

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 7G      


    command:
      - postgres
      - -c
      - shared_buffers=3GB
      - -c
      - effective_cache_size=7GB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - work_mem=16MB
      - -c
      - max_connections=100
      - -c
      - wal_buffers=16MB
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - min_wal_size=1GB
      - -c
      - max_wal_size=4GB
      - -c
      - random_page_cost=1.1
      - -c
      - effective_io_concurrency=200
      - -c
      - default_statistics_target=100

volumes:
  volumes_postgres_16:

networks:
  postgres_16_network:
    name: postgres_16_network
    driver: bridge