services:
  # ============================================================
  # container_postgres_16
  # ============================================================
  container_postgres_16:
    image: postgres:16
    container_name: container_postgres_16
    restart: unless-stopped

    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres

    networks:
      - postgres_16_network

    volumes:
      - volumes_postgres_16:/var/lib/postgresql/data

    ports:
      - "5632:5432"


volumes:
  volumes_postgres_16:

networks:
  postgres_16_network:
    name: postgres_16_network
    driver: bridge